language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - extra-android-m2repository
    - extra-google-m2repository

    # The SDK version used to compile your project
    - android-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23

  licenses:
      - android-sdk-license-.+

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - echo $ADB_INSTALL_TIMEOUT
  - android list target
  - ./gradlew clean
  - ./gradlew assembleDebug
  - ./gradlew assembleDebugAndroidTest
  - adb install app/build/outputs/apk/app-debug.apk
  - adb install app/build/outputs/apk/app-debug-androidTest-unaligned.apk
  - adb shell am instrument -w com.example.blah.mobilestudio.test/android.support.test.runner.AndroidJUnitRunner
  - ./gradlew uninstallAll

